# Sort data by state alphabetically
alpha_state <- data[order(data$State),]
# Remove index generated by sort
row.names(alpha_state) <- NULL
# Remove periods from column names
names(alpha_state) <- gsub("\\.", " ", names(alpha_state))
# Make table
knitr::kable(alpha_state, format = "latex", booktabs = T, caption='Appendix') %>%
  add_header_above(c(" " = 2, "Raw Values" = 4, "Adjusted per 100,000 people per state" = 3)) %>%
  kable_styling(latex_options = c("scale_down"))
